language: python
python:
  - 3.5
  - 3.7
  - 3.8
  - 3.9

install:
  - python setup.py install
  - pip install 'pytest>=5.2'
  - pip install pytest-cov
  - pip install codecov

script:
  - py.test --cov=inscriptis ./tests

# Push the results back to codecov
after_success:
  - codecov
